-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceFoundation/maintenance/db/sql/bs_settings3.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_settings3 (
  s_name VARCHAR(255) NOT NULL,
  s_value MEDIUMBLOB NOT NULL,
  PRIMARY KEY(s_name)
) /*$wgDBTableOptions*/;
